name: Sync to portfolio-replica

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout principal repo
        uses: actions/checkout@v3

      - name: Push to portfolio-replica
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@users.noreply.github.com'

          git clone https://x-access-token:${{ secrets.REPLICA_TOKEN }}@github.com/leoferamos/portfolio-replica.git replica
          rsync -av --exclude='.git' --exclude='.github' ./ ./replica/
          cd replica
          git add .
          git commit -m "Sync from portfolio" || echo "No changes to commit"
          git push origin main
